### ISSUE TITLE
personal access token...

### ISSUE THREAD

**Issue by myoung3** [noamross/repro-template#1]
randomly stumbled on this repo (it came up on my feed since someone I follow starred it) and was curious since I'm using containers for R projects. stumbled upon this:

https://github.com/noamross/repro-template/blob/main/.env

you'll want to cancel that github token immediately

**Comment by noamross** [comment]
Crap, thanks! I thought I had encrypted that properly

**Comment by noamross** [comment]
New PAT, now properly encrypted with git-crypt in `.gitattributes`: https://github.com/noamross/repro-template/blob/main/.gitattributes
